# This file was auto-generated by Fern from our API Definition.

import typing

SarvamModelIds = typing.Union[
    typing.Literal["sarvam-m", "gemma-4b", "gemma-12b", "sarvam-30b", "sarvam-100b"], typing.Any
]
